services:
  analysis-env:
    image: skysheng7/ai_bias:cb8895e
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
