services:
  analysis-env:
    image: skysheng7/ai_bias:fd72c23
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
