################################################################################
# Build Configuration
################################################################################

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

################################################################################
# Project Configuration
################################################################################

[project]
name = "AI_representation_bias_in_farming"

dynamic = ["version"]

description = "This project explores the bias text-to-image generative AI models have about livestock farming. "
authors = [
    { name = "Kehan (Sky) Sheng", email = "skysheng7@gmail.com" },
]
license = "MIT"
readme = {"file" = "README.md", "content-type" = "text/markdown"}
requires-python = ">=3.11"
# Please consult https://pypi.org/classifiers/ for a full list.
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
# TODO: add keywords
keywords = []
# TODO: add dependencies
dependencies = []

[project.urls]
Homepage = "https://github.com/skysheng7/AI_representation_bias_in_farming"
"Source Code" = "https://github.com/skysheng7/AI_representation_bias_in_farming"
"Bug Tracker" = "https://github.com/skysheng7/AI_representation_bias_in_farming/issues"

