"""Library of functions used to count the occurance of words in each revised prompt/image descriptions
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# import the megadata dataframe, and sort by the length of revised prompts
from pathlib import Path

megadata_file = Path(".") / "results" / "megadata" / "image_megadata.csv"
megadata = pd.read_csv(megadata_file, header=0)


def count_word_freq_in_revised_prompt(megadata, min_freq=20):
    """This function creates bag of word to count if certain words appear in the text
    description in each row.

    Parameters:
    megadata (dataframe): the dataframe recording megadata about generated images
    min_freq (int, optional): sets a minimum document frequency threshold,
                            a filter that says "only keep words that appear in
                            at least min_freq documents." Defaults to 10.

    Returns:
    pandas.DataFrame: Original megadata with additional columns for word frequencies
    array: the bag of words generated by vectorization
    """

    # Create the vectorizer with specified parameters
    vec = CountVectorizer(min_df=min_freq, binary=True, stop_words="english")

    # Extract the revised prompts and convert them to a list
    revised_prompts = megadata["revised_prompt"].fillna(
        ""
    )  # Handle any potential NaN values

    # Fit and transform the revised prompts into a binary bag of words
    prompts_vec = vec.fit_transform(revised_prompts)

    # The bag of words generated by vec
    bag_of_words = vec.get_feature_names_out()

    # Now we need to replace 'country' with 'Country' in this list of feature names
    # this is because "country" column already exist in the megadata frame
    bag_of_words = [
        word.replace("country", "Country") if word == "country" else word
        for word in bag_of_words
    ]

    # Create a DataFrame from the vectorized prompts
    # Each column will represent a word, and each row will show whether that word appears
    prompts_vec_df = pd.DataFrame(
        data=prompts_vec.toarray(),
        columns=bag_of_words,
        index=megadata.index,  # Preserve the original index for proper alignment
    )

    # Combine the original megadata with the word frequency data
    # Using axis=1 to concatenate horizontally (add new columns)
    result_df = pd.concat([megadata, prompts_vec_df], axis=1)

    return (result_df, bag_of_words)


def create_detailed_word_summary(result_df, feature_names):
    """
    Creates a summary DataFrame showing word frequencies for each unique combination of
    categorical variables, with an additional column listing the top 20 most frequent
    words and their frequencies as a readable string.

    Parameters:
    result_df (DataFrame): The DataFrame output from count_word_freq_in_revised_prompt
    feature_names (array): The vocabulary from vec.get_feature_names_out()

    Returns:
    DataFrame: A summary with base columns, word frequency columns, and a top_20_words column
    """
    # Define our grouping columns for finding unique instances
    group_columns = ["generation_type", "country", "farm_type", "prompt", "model"]

    # Initialize a list to store our summary data
    summary_data = []

    # Find unique combinations of our grouping columns
    unique_combinations = result_df[group_columns].drop_duplicates()

    # For each unique combination in our data
    for _, combo in unique_combinations.iterrows():
        # Get all rows matching this combination
        matching_rows = result_df[
            (result_df["generation_type"] == combo["generation_type"])
            & (result_df["country"] == combo["country"])
            & (result_df["farm_type"] == combo["farm_type"])
            & (result_df["prompt"] == combo["prompt"])
            & (result_df["model"] == combo["model"])
        ]

        # Start with the categorical information
        row_dict = combo.to_dict()

        # Calculate word frequencies for this combination
        word_freq_dict = {}
        for word in feature_names:
            freq = matching_rows[word].sum()
            row_dict[word] = freq
            word_freq_dict[word] = freq

        # Create the top 20 words summary
        # Sort words by frequency and get top 20
        top_words = sorted(word_freq_dict.items(), key=lambda x: (-x[1], x[0]))[:20]

        # Format the top words as a readable string
        # Example format: "word1 (10), word2 (8), word3 (5)..."
        top_words_str = ", ".join(f"{word} ({freq})" for word, freq in top_words)

        # Add the top words summary to our row dictionary
        row_dict["top_20_words"] = top_words_str

        summary_data.append(row_dict)

    # Create our summary DataFrame
    summary_df = pd.DataFrame(summary_data)

    # Ensure columns are in a logical order: grouping columns first,
    # then all word columns, then top_20_words at the end
    final_column_order = (
        group_columns
        + [col for col in feature_names if col in summary_df.columns]
        + ["top_20_words"]
    )
    summary_df = summary_df[final_column_order]

    return summary_df


# Example usage:
result_df, feature_names = count_word_freq_in_revised_prompt(megadata, min_freq=20)
summary_df = create_detailed_word_summary(result_df, feature_names)
