blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/skysheng7/ai's-representation-bias-about-livestock-farming/discussions
    about: Please ask and answer questions here.
