"""
Generate plot grids to visualize the megadata from generaetd images
"""

import pandas as pd
from pathlib import Path
import click

from AI_representation_bias_in_farming import utils
from AI_representation_bias_in_farming import module4_plot_generation


@click.command()
def main():
    """generate plot grid
    # Model 1: DALL·E 3
    # plot 4 columns:
    #                prompt (original prompt),
    #                revised prompt (wordcloud of the automatically revised prompt from DALL-E 3),
    #                example image (a randomly drawn image example showing the output from thie prompt),
    #                Description (wordcloud of text description generated by GPT-4o image-to-text model)
    #
    # Model 2: Stable Diffusion 3.5-large
    # plot 3 columns because sd-3.5-large does not automatically revise prompts:
    #                prompt (original prompt),
    #                example image (a randomly drawn image example showing the output from thie prompt),
    #                Description (wordcloud of text description generated by GPT-4o image-to-text model)
    """
    # list of countries with the biggest number of dairy cows and pigs in North America, Europe and Oceania
    countries_by_farm_type = {
        "dairy": ["the United States", "Germany", "New Zealand"],
        "pig": ["the United States", "Spain", "Australia"],
    }

    ######################
    ######################
    ###### DALLE- 3#######
    ######################
    ######################

    # DALLE-3 plot grid should have 4 columns. Stable Diffusion plot grid should have 3 columns
    model = "dall-e-3"
    num_cols = 4
    top_word_n_to_show = 20

    # import the megadata dataframe
    megadata = utils.read_megadata()
    revised_prompt_2gram_summary = utils.read_csv_file(
        "revised_prompt_2gram_freq_summary.csv"
    )
    gpt4o_description_2gram_summary = utils.read_csv_file(
        "GPT4o_description_2gram_freq_summary.csv"
    )

    ### Model 1 prompt type 1: reality prompt
    # Define generation types and farm types
    gen_types = ["reality", "reality_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt DALL·E 3 for a realistic farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=17,
    )
    print("Generated plot: Prompt DALL·E 3 for a realistic farm")

    ### Model 1 prompt type 2: basic prompt
    # Define generation types and farm types
    gen_types = ["basic", "basic_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt DALL·E 3 for a general farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print("Generated plot: Prompt DALL·E 3 for a general farm")

    ### Model 1 prompt type 3: typical prompt
    # Define generation types and farm types
    gen_types = ["typical", "typical_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt DALL·E 3 for a typical farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=678,
    )
    print("Generated plot: Prompt DALL·E 3 for a typical farm")

    ### Model 1 prompt type 1 + country: reality by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["reality_country", "reality_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for realistic {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for realistic {farm_type} farms in 3 different countries"
    )

    ### Model 1 prompt type 1 + country: reality by country for pig prompt
    # Define generation types and farm types
    gen_types = ["reality_country", "reality_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for realistic {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=108,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for realistic {farm_type} farms in 3 different countries"
    )

    ### Model 1 prompt type 2 + country: basic by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["basic_country", "basic_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for general {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=888,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for general {farm_type} farms in 3 different countries"
    )

    ### Model 1 prompt type 2 + country: basic by country for pig prompt
    # Define generation types and farm types
    gen_types = ["basic_country", "basic_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for general {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=788,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for general {farm_type} farms in 3 different countries"
    )

    ### Model 1 prompt type 3 + country: typical by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["typical_country", "typical_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for typical {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=7,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for typical {farm_type} farms in 3 different countries"
    )

    ### Model 1 prompt type 3 + country: typical by country for pig prompt
    # Define generation types and farm types
    gen_types = ["typical_country", "typical_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt DALL·E 3 for typical {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=708,
    )
    print(
        f"Generated plot: Prompt DALL·E 3 for typical {farm_type} farms in 3 different countries"
    )

    ##################################
    ##################################
    ####Stable Diffusion 3.5-large####
    ##################################
    ##################################

    # DALLE-3 plot grid should have 4 columns. Stable Diffusion plot grid should have 3 columns
    model = "sd3.5-large"
    num_cols = 3

    ### Model 2 prompt type 1: reality prompt
    # Define generation types and farm types
    gen_types = ["reality", "reality_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt Stable Diffusion 3.5-large for a realistic farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=7,
    )
    print("Generated plot: Prompt Stable Diffusion 3.5-large for a realistic farm")

    ### Model 2 prompt type 2: basic prompt
    # Define generation types and farm types
    gen_types = ["basic", "basic_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt Stable Diffusion 3.5-large for a general farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print("Generated plot: Prompt Stable Diffusion 3.5-large for a general farm")

    ### Model 2 prompt type 3: typical prompt
    # Define generation types and farm types
    gen_types = ["typical", "typical_no_revise"]
    farm_types = megadata["farm_type"].unique()
    title = "Prompt Stable Diffusion 3.5-large for a typical farm"
    module4_plot_generation.plot_grid(
        megadata,
        gen_types,
        farm_types,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=7,
    )
    print("Generated plot: Prompt Stable Diffusion 3.5-large for a typical farm")

    ### Model 2 prompt type 1 + country: reality by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["reality_country", "reality_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for realistic {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for realistic {farm_type} farms in 3 different countries"
    )

    ### Model 2 prompt type 1 + country: reality by country for pig prompt
    # Define generation types and farm types
    gen_types = ["reality_country", "reality_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for realistic {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=800,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for realistic {farm_type} farms in 3 different countries"
    )

    ### Model 2 prompt type 2 + country: basic by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["basic_country", "basic_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for general {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for general {farm_type} farms in 3 different countries"
    )

    ### Model 2 prompt type 2 + country: basic by country for pig prompt
    # Define generation types and farm types
    gen_types = ["basic_country", "basic_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for general {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=1,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for general {farm_type} farms in 3 different countries"
    )

    ### Model 2 prompt type 3 + country: typical by country for dairy prompt
    # Define generation types and farm types
    gen_types = ["typical_country", "typical_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[0]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for typical {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=7,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for typical {farm_type} farms in 3 different countries"
    )

    ### Model 2 prompt type 3 + country: typical by country for pig prompt
    # Define generation types and farm types
    gen_types = ["typical_country", "typical_country_no_revise"]
    farm_type = megadata["farm_type"].unique()[1]
    countries = countries_by_farm_type[farm_type]
    title = f"Prompt Stable Diffusion 3.5-large for typical {farm_type} farms in 3 different countries"
    module4_plot_generation.plot_grid_country(
        megadata,
        gen_types,
        farm_type,
        countries,
        title,
        revised_prompt_2gram_summary,
        gpt4o_description_2gram_summary,
        top_word_n_to_show,
        col_num=num_cols,
        model=model,
        seed=707,
    )
    print(
        f"Generated plot: Prompt Stable Diffusion 3.5-large for typical {farm_type} farms in 3 different countries"
    )


# Only execute this code if the script is run directly
if __name__ == "__main__":
    main()
